// Monaco Editor Comprehensive Auto-Completion & IntelliSense Provider
// Supports: Java, C++, C, Python, JavaScript, TypeScript, C#, Go, Rust, Kotlin, Swift, PHP, Ruby, Scala, Dart, SQL, HTML, CSS

import type * as Monaco from "monaco-editor";

type MonacoInstance = typeof Monaco;

interface CompletionEntry {
  label: string;
  kind?: string; // 'keyword' | 'class' | 'function' | 'snippet' | 'type' | 'variable' | 'interface' | 'module'
  detail?: string;
  documentation?: string;
  insertText?: string;
  isSnippet?: boolean;
}

// ── Language Definitions ────────────────────────────────────────────────────────

const JAVA_COMPLETIONS: CompletionEntry[] = [
  // Keywords
  { label: "abstract", kind: "keyword", detail: "keyword" },
  { label: "assert", kind: "keyword", detail: "keyword" },
  { label: "boolean", kind: "type", detail: "primitive type" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "byte", kind: "type", detail: "primitive type" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "char", kind: "type", detail: "primitive type" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName} {\n\t$0\n}", isSnippet: true },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "double", kind: "type", detail: "primitive type" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "extends", kind: "keyword", detail: "keyword" },
  { label: "final", kind: "keyword", detail: "keyword" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "float", kind: "type", detail: "primitive type" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "goto", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "implements", kind: "keyword", detail: "keyword" },
  { label: "import", kind: "keyword", detail: "keyword", insertText: "import ${1:package};\n", isSnippet: true },
  { label: "instanceof", kind: "keyword", detail: "keyword" },
  { label: "int", kind: "type", detail: "primitive type" },
  { label: "interface", kind: "keyword", detail: "keyword" },
  { label: "long", kind: "type", detail: "primitive type" },
  { label: "native", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "package", kind: "keyword", detail: "keyword" },
  { label: "private", kind: "keyword", detail: "keyword" },
  { label: "protected", kind: "keyword", detail: "keyword" },
  { label: "public", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "short", kind: "type", detail: "primitive type" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "strictfp", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "synchronized", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "throws", kind: "keyword", detail: "keyword" },
  { label: "transient", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try {\n\t$1\n} catch (${2:Exception} e) {\n\t${3:e.printStackTrace();}\n}", isSnippet: true },
  { label: "var", kind: "type", detail: "local variable type" },
  { label: "void", kind: "type", detail: "keyword" },
  { label: "volatile", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "record", kind: "keyword", detail: "keyword" },
  { label: "sealed", kind: "keyword", detail: "keyword" },
  { label: "permits", kind: "keyword", detail: "keyword" },
  { label: "non-sealed", kind: "keyword", detail: "keyword" },
  { label: "yield", kind: "keyword", detail: "keyword" },

  // Java Standard Classes (Matches screenshot & standard library)
  { label: "Class", kind: "class", detail: "java.lang.Class" },
  { label: "ClassCastException", kind: "class", detail: "java.lang.ClassCastException" },
  { label: "ClassCircularityError", kind: "class", detail: "java.lang.ClassCircularityError" },
  { label: "ClassFormatError", kind: "class", detail: "java.lang.ClassFormatError" },
  { label: "ClassLoader", kind: "class", detail: "java.lang.ClassLoader" },
  { label: "ClassNotFoundException", kind: "class", detail: "java.lang.ClassNotFoundException" },
  { label: "NoClassDefFoundError", kind: "class", detail: "java.lang.NoClassDefFoundError" },
  { label: "String", kind: "class", detail: "java.lang.String" },
  { label: "StringBuilder", kind: "class", detail: "java.lang.StringBuilder" },
  { label: "StringBuffer", kind: "class", detail: "java.lang.StringBuffer" },
  { label: "System", kind: "class", detail: "java.lang.System" },
  { label: "Scanner", kind: "class", detail: "java.util.Scanner" },
  { label: "Math", kind: "class", detail: "java.lang.Math" },
  { label: "Integer", kind: "class", detail: "java.lang.Integer" },
  { label: "Double", kind: "class", detail: "java.lang.Double" },
  { label: "Long", kind: "class", detail: "java.lang.Long" },
  { label: "Float", kind: "class", detail: "java.lang.Float" },
  { label: "Boolean", kind: "class", detail: "java.lang.Boolean" },
  { label: "Character", kind: "class", detail: "java.lang.Character" },
  { label: "Object", kind: "class", detail: "java.lang.Object" },
  { label: "Thread", kind: "class", detail: "java.lang.Thread" },
  { label: "Runnable", kind: "interface", detail: "java.lang.Runnable" },
  { label: "Exception", kind: "class", detail: "java.lang.Exception" },
  { label: "RuntimeException", kind: "class", detail: "java.lang.RuntimeException" },
  { label: "Throwable", kind: "class", detail: "java.lang.Throwable" },
  { label: "Error", kind: "class", detail: "java.lang.Error" },
  { label: "List", kind: "interface", detail: "java.util.List" },
  { label: "ArrayList", kind: "class", detail: "java.util.ArrayList" },
  { label: "LinkedList", kind: "class", detail: "java.util.LinkedList" },
  { label: "Set", kind: "interface", detail: "java.util.Set" },
  { label: "HashSet", kind: "class", detail: "java.util.HashSet" },
  { label: "TreeSet", kind: "class", detail: "java.util.TreeSet" },
  { label: "Map", kind: "interface", detail: "java.util.Map" },
  { label: "HashMap", kind: "class", detail: "java.util.HashMap" },
  { label: "TreeMap", kind: "class", detail: "java.util.TreeMap" },
  { label: "Queue", kind: "interface", detail: "java.util.Queue" },
  { label: "PriorityQueue", kind: "class", detail: "java.util.PriorityQueue" },
  { label: "Stack", kind: "class", detail: "java.util.Stack" },
  { label: "Arrays", kind: "class", detail: "java.util.Arrays" },
  { label: "Collections", kind: "class", detail: "java.util.Collections" },
  { label: "Optional", kind: "class", detail: "java.util.Optional" },
  { label: "Stream", kind: "interface", detail: "java.util.stream.Stream" },
  { label: "Collectors", kind: "class", detail: "java.util.stream.Collectors" },
  { label: "BufferedReader", kind: "class", detail: "java.io.BufferedReader" },
  { label: "InputStreamReader", kind: "class", detail: "java.io.InputStreamReader" },
  { label: "PrintWriter", kind: "class", detail: "java.io.PrintWriter" },

  // Snippets
  { label: "psvm", kind: "snippet", detail: "main method", insertText: "public static void main(String[] args) {\n\t$0\n}", isSnippet: true },
  { label: "sout", kind: "snippet", detail: "System.out.println", insertText: "System.out.println($1);", isSnippet: true },
  { label: "sysout", kind: "snippet", detail: "System.out.println", insertText: "System.out.println($1);", isSnippet: true },
  { label: "scanner", kind: "snippet", detail: "Scanner sc = new Scanner(System.in);", insertText: "Scanner ${1:sc} = new Scanner(System.in);", isSnippet: true },
  { label: "fori", kind: "snippet", detail: "indexed for loop", insertText: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "fore", kind: "snippet", detail: "for-each loop", insertText: "for (${1:Type} ${2:item} : ${3:collection}) {\n\t$0\n}", isSnippet: true },
];

const CPP_COMPLETIONS: CompletionEntry[] = [
  // Keywords
  { label: "alignas", kind: "keyword", detail: "keyword" },
  { label: "alignof", kind: "keyword", detail: "keyword" },
  { label: "asm", kind: "keyword", detail: "keyword" },
  { label: "auto", kind: "type", detail: "type deduction" },
  { label: "bool", kind: "type", detail: "primitive type" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "char", kind: "type", detail: "primitive type" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName} {\npublic:\n\t$0\n};", isSnippet: true },
  { label: "concept", kind: "keyword", detail: "keyword" },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "const_cast", kind: "keyword", detail: "keyword" },
  { label: "constexpr", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "decltype", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "delete", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "double", kind: "type", detail: "primitive type" },
  { label: "dynamic_cast", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "explicit", kind: "keyword", detail: "keyword" },
  { label: "export", kind: "keyword", detail: "keyword" },
  { label: "extern", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "float", kind: "type", detail: "primitive type" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ++${1:i}) {\n\t$0\n}", isSnippet: true },
  { label: "friend", kind: "keyword", detail: "keyword" },
  { label: "goto", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "inline", kind: "keyword", detail: "keyword" },
  { label: "int", kind: "type", detail: "primitive type" },
  { label: "long", kind: "type", detail: "primitive type" },
  { label: "mutable", kind: "keyword", detail: "keyword" },
  { label: "namespace", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "noexcept", kind: "keyword", detail: "keyword" },
  { label: "nullptr", kind: "keyword", detail: "keyword" },
  { label: "operator", kind: "keyword", detail: "keyword" },
  { label: "private", kind: "keyword", detail: "keyword" },
  { label: "protected", kind: "keyword", detail: "keyword" },
  { label: "public", kind: "keyword", detail: "keyword" },
  { label: "reinterpret_cast", kind: "keyword", detail: "keyword" },
  { label: "requires", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "short", kind: "type", detail: "primitive type" },
  { label: "signed", kind: "type", detail: "primitive type" },
  { label: "sizeof", kind: "keyword", detail: "keyword" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "static_assert", kind: "keyword", detail: "keyword" },
  { label: "static_cast", kind: "keyword", detail: "keyword" },
  { label: "struct", kind: "keyword", detail: "keyword", insertText: "struct ${1:StructName} {\n\t$0\n};", isSnippet: true },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "template", kind: "keyword", detail: "keyword", insertText: "template <typename ${1:T}>\n", isSnippet: true },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try {\n\t$1\n} catch (const ${2:std::exception}& e) {\n\t$0\n}", isSnippet: true },
  { label: "typedef", kind: "keyword", detail: "keyword" },
  { label: "typeid", kind: "keyword", detail: "keyword" },
  { label: "typename", kind: "keyword", detail: "keyword" },
  { label: "union", kind: "keyword", detail: "keyword" },
  { label: "unsigned", kind: "type", detail: "primitive type" },
  { label: "using", kind: "keyword", detail: "keyword" },
  { label: "virtual", kind: "keyword", detail: "keyword" },
  { label: "void", kind: "type", detail: "keyword" },
  { label: "volatile", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while (${1:condition}) {\n\t$0\n}", isSnippet: true },

  // C++ Standard Library
  { label: "std", kind: "module", detail: "namespace std" },
  { label: "cout", kind: "variable", detail: "std::cout (ostream)" },
  { label: "cin", kind: "variable", detail: "std::cin (istream)" },
  { label: "cerr", kind: "variable", detail: "std::cerr (ostream)" },
  { label: "endl", kind: "function", detail: "std::endl" },
  { label: "string", kind: "class", detail: "std::string" },
  { label: "vector", kind: "class", detail: "std::vector<T>", insertText: "vector<${1:int}> ${2:v};", isSnippet: true },
  { label: "map", kind: "class", detail: "std::map<K, V>" },
  { label: "unordered_map", kind: "class", detail: "std::unordered_map<K, V>" },
  { label: "set", kind: "class", detail: "std::set<T>" },
  { label: "unordered_set", kind: "class", detail: "std::unordered_set<T>" },
  { label: "pair", kind: "class", detail: "std::pair<T1, T2>" },
  { label: "make_pair", kind: "function", detail: "std::make_pair" },
  { label: "tuple", kind: "class", detail: "std::tuple" },
  { label: "queue", kind: "class", detail: "std::queue<T>" },
  { label: "priority_queue", kind: "class", detail: "std::priority_queue<T>" },
  { label: "stack", kind: "class", detail: "std::stack<T>" },
  { label: "deque", kind: "class", detail: "std::deque<T>" },
  { label: "algorithm", kind: "module", detail: "<algorithm>" },
  { label: "sort", kind: "function", detail: "std::sort(begin, end)" },
  { label: "reverse", kind: "function", detail: "std::reverse(begin, end)" },
  { label: "max", kind: "function", detail: "std::max(a, b)" },
  { label: "min", kind: "function", detail: "std::min(a, b)" },
  { label: "swap", kind: "function", detail: "std::swap(a, b)" },
  { label: "binary_search", kind: "function", detail: "std::binary_search" },
  { label: "lower_bound", kind: "function", detail: "std::lower_bound" },
  { label: "upper_bound", kind: "function", detail: "std::upper_bound" },
  { label: "size_t", kind: "type", detail: "size_t" },

  // Snippets
  { label: "main", kind: "snippet", detail: "main() function", insertText: "int main() {\n\t$0\n\treturn 0;\n}", isSnippet: true },
  { label: "include", kind: "snippet", detail: "#include standard competitive header", insertText: "#include <iostream>\n#include <vector>\n#include <algorithm>\n\nusing namespace std;\n\n$0", isSnippet: true },
  { label: "couts", kind: "snippet", detail: "cout with newline", insertText: "cout << ${1:\"\"} << endl;", isSnippet: true },
  { label: "cins", kind: "snippet", detail: "cin statement", insertText: "cin >> ${1:var};", isSnippet: true },
];

const C_COMPLETIONS: CompletionEntry[] = [
  { label: "auto", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "char", kind: "type", detail: "primitive type" },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "double", kind: "type", detail: "primitive type" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "extern", kind: "keyword", detail: "keyword" },
  { label: "float", kind: "type", detail: "primitive type" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "goto", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "inline", kind: "keyword", detail: "keyword" },
  { label: "int", kind: "type", detail: "primitive type" },
  { label: "long", kind: "type", detail: "primitive type" },
  { label: "register", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "short", kind: "type", detail: "primitive type" },
  { label: "signed", kind: "type", detail: "primitive type" },
  { label: "sizeof", kind: "keyword", detail: "keyword" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "struct", kind: "keyword", detail: "keyword", insertText: "struct ${1:Name} {\n\t$0\n};", isSnippet: true },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "typedef", kind: "keyword", detail: "keyword" },
  { label: "union", kind: "keyword", detail: "keyword" },
  { label: "unsigned", kind: "type", detail: "primitive type" },
  { label: "void", kind: "type", detail: "keyword" },
  { label: "volatile", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "NULL", kind: "keyword", detail: "((void*)0)" },

  // C Standard Library
  { label: "printf", kind: "function", detail: "printf(format, ...)", insertText: "printf(\"${1:%d}\\n\", ${2:var});", isSnippet: true },
  { label: "scanf", kind: "function", detail: "scanf(format, ...)", insertText: "scanf(\"${1:%d}\", &${2:var});", isSnippet: true },
  { label: "malloc", kind: "function", detail: "malloc(size_t size)", insertText: "(${1:int*})malloc(sizeof(${1:int}) * ${2:n});", isSnippet: true },
  { label: "calloc", kind: "function", detail: "calloc(size_t num, size_t size)" },
  { label: "realloc", kind: "function", detail: "realloc(void* ptr, size_t size)" },
  { label: "free", kind: "function", detail: "free(ptr)", insertText: "free(${1:ptr});", isSnippet: true },
  { label: "exit", kind: "function", detail: "exit(status)" },
  { label: "strlen", kind: "function", detail: "strlen(const char* s)" },
  { label: "strcpy", kind: "function", detail: "strcpy(dest, src)" },
  { label: "strcmp", kind: "function", detail: "strcmp(s1, s2)" },
  { label: "strcat", kind: "function", detail: "strcat(dest, src)" },
  { label: "memset", kind: "function", detail: "memset(ptr, val, size)" },
  { label: "memcpy", kind: "function", detail: "memcpy(dest, src, size)" },
  { label: "FILE", kind: "type", detail: "FILE struct" },

  // Snippets
  { label: "main", kind: "snippet", detail: "main() function", insertText: "int main() {\n\t$0\n\treturn 0;\n}", isSnippet: true },
  { label: "include", kind: "snippet", detail: "#include <stdio.h>", insertText: "#include <stdio.h>\n#include <stdlib.h>\n#include <string.h>\n\n$0", isSnippet: true },
];

const PYTHON_COMPLETIONS: CompletionEntry[] = [
  // Keywords
  { label: "and", kind: "keyword", detail: "keyword" },
  { label: "as", kind: "keyword", detail: "keyword" },
  { label: "assert", kind: "keyword", detail: "keyword" },
  { label: "async", kind: "keyword", detail: "keyword" },
  { label: "await", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName}:\n    def __init__(self${2:, args}):\n        $0", isSnippet: true },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "def", kind: "keyword", detail: "keyword", insertText: "def ${1:function_name}(${2:params}):\n    $0", isSnippet: true },
  { label: "del", kind: "keyword", detail: "keyword" },
  { label: "elif", kind: "keyword", detail: "keyword", insertText: "elif ${1:condition}:\n    $0", isSnippet: true },
  { label: "else", kind: "keyword", detail: "keyword", insertText: "else:\n    $0", isSnippet: true },
  { label: "except", kind: "keyword", detail: "keyword", insertText: "except ${1:Exception} as ${2:e}:\n    $0", isSnippet: true },
  { label: "False", kind: "keyword", detail: "boolean" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for ${1:item} in ${2:iterable}:\n    $0", isSnippet: true },
  { label: "from", kind: "keyword", detail: "keyword" },
  { label: "global", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if ${1:condition}:\n    $0", isSnippet: true },
  { label: "import", kind: "keyword", detail: "keyword" },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "is", kind: "keyword", detail: "keyword" },
  { label: "lambda", kind: "keyword", detail: "keyword", insertText: "lambda ${1:x}: ${2:x}", isSnippet: true },
  { label: "None", kind: "keyword", detail: "NoneType" },
  { label: "nonlocal", kind: "keyword", detail: "keyword" },
  { label: "not", kind: "keyword", detail: "keyword" },
  { label: "or", kind: "keyword", detail: "keyword" },
  { label: "pass", kind: "keyword", detail: "keyword" },
  { label: "raise", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "True", kind: "keyword", detail: "boolean" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try:\n    ${1:pass}\nexcept ${2:Exception} as ${3:e}:\n    $0", isSnippet: true },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while ${1:condition}:\n    $0", isSnippet: true },
  { label: "with", kind: "keyword", detail: "keyword", insertText: "with open(${1:filename}, \"${2:r}\") as ${3:f}:\n    $0", isSnippet: true },
  { label: "yield", kind: "keyword", detail: "keyword" },
  { label: "match", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },

  // Built-ins & standard functions
  { label: "print", kind: "function", detail: "print(*objects, sep=' ', end='\\n')", insertText: "print($1)", isSnippet: true },
  { label: "input", kind: "function", detail: "input(prompt='')", insertText: "input($1)", isSnippet: true },
  { label: "len", kind: "function", detail: "len(s)" },
  { label: "range", kind: "function", detail: "range(stop) or range(start, stop, step)", insertText: "range(${1:n})", isSnippet: true },
  { label: "str", kind: "class", detail: "str(object='')" },
  { label: "int", kind: "class", detail: "int(x=0)" },
  { label: "float", kind: "class", detail: "float(x=0.0)" },
  { label: "bool", kind: "class", detail: "bool(x=False)" },
  { label: "list", kind: "class", detail: "list(iterable=())" },
  { label: "dict", kind: "class", detail: "dict(**kwargs)" },
  { label: "set", kind: "class", detail: "set(iterable=())" },
  { label: "tuple", kind: "class", detail: "tuple(iterable=())" },
  { label: "enumerate", kind: "function", detail: "enumerate(iterable, start=0)" },
  { label: "zip", kind: "function", detail: "zip(*iterables)" },
  { label: "map", kind: "function", detail: "map(function, iterable)" },
  { label: "filter", kind: "function", detail: "filter(function, iterable)" },
  { label: "sorted", kind: "function", detail: "sorted(iterable, key=None, reverse=False)" },
  { label: "reversed", kind: "function", detail: "reversed(sequence)" },
  { label: "sum", kind: "function", detail: "sum(iterable, start=0)" },
  { label: "min", kind: "function", detail: "min(iterable)" },
  { label: "max", kind: "function", detail: "max(iterable)" },
  { label: "abs", kind: "function", detail: "abs(x)" },
  { label: "round", kind: "function", detail: "round(number, ndigits=None)" },
  { label: "all", kind: "function", detail: "all(iterable)" },
  { label: "any", kind: "function", detail: "any(iterable)" },
  { label: "isinstance", kind: "function", detail: "isinstance(object, classinfo)" },
  { label: "open", kind: "function", detail: "open(file, mode='r')" },
  { label: "self", kind: "variable", detail: "instance reference" },

  // Snippets
  { label: "main", kind: "snippet", detail: "if __name__ == '__main__':", insertText: "if __name__ == \"__main__\":\n    $0", isSnippet: true },
  { label: "mapint", kind: "snippet", detail: "map(int, input().split())", insertText: "map(int, input().split())", isSnippet: false },
  { label: "listint", kind: "snippet", detail: "list(map(int, input().split()))", insertText: "list(map(int, input().split()))", isSnippet: false },
];

const JAVASCRIPT_COMPLETIONS: CompletionEntry[] = [
  { label: "async", kind: "keyword", detail: "keyword" },
  { label: "await", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName} {\n\tconstructor(${2:args}) {\n\t\t$0\n\t}\n}", isSnippet: true },
  { label: "const", kind: "keyword", detail: "keyword", insertText: "const ${1:name} = ${2:value};", isSnippet: true },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "debugger", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "delete", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "export", kind: "keyword", detail: "keyword" },
  { label: "extends", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "boolean" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (let ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "function", kind: "keyword", detail: "keyword", insertText: "function ${1:name}(${2:params}) {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "import", kind: "keyword", detail: "keyword", insertText: "import ${1:item} from \"${2:module}\";", isSnippet: true },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "instanceof", kind: "keyword", detail: "keyword" },
  { label: "let", kind: "keyword", detail: "keyword", insertText: "let ${1:name} = ${2:value};", isSnippet: true },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "null" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "boolean" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try {\n\t$1\n} catch (${2:error}) {\n\t$0\n}", isSnippet: true },
  { label: "typeof", kind: "keyword", detail: "keyword" },
  { label: "undefined", kind: "keyword", detail: "undefined" },
  { label: "var", kind: "keyword", detail: "keyword" },
  { label: "void", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "yield", kind: "keyword", detail: "keyword" },

  // Objects & APIs
  { label: "console", kind: "class", detail: "Console" },
  { label: "log", kind: "function", detail: "console.log", insertText: "console.log($1);", isSnippet: true },
  { label: "Math", kind: "class", detail: "Math object" },
  { label: "JSON", kind: "class", detail: "JSON object" },
  { label: "Promise", kind: "class", detail: "Promise constructor", insertText: "new Promise((resolve, reject) => {\n\t$0\n})", isSnippet: true },
  { label: "Array", kind: "class", detail: "Array" },
  { label: "Object", kind: "class", detail: "Object" },
  { label: "String", kind: "class", detail: "String" },
  { label: "Number", kind: "class", detail: "Number" },
  { label: "Boolean", kind: "class", detail: "Boolean" },
  { label: "Map", kind: "class", detail: "Map" },
  { label: "Set", kind: "class", detail: "Set" },
  { label: "setTimeout", kind: "function", detail: "setTimeout(callback, delay)" },
  { label: "setInterval", kind: "function", detail: "setInterval(callback, delay)" },
  { label: "parseInt", kind: "function", detail: "parseInt(string, radix)" },
  { label: "parseFloat", kind: "function", detail: "parseFloat(string)" },

  // Snippets
  { label: "clg", kind: "snippet", detail: "console.log()", insertText: "console.log($1);", isSnippet: true },
  { label: "arrow", kind: "snippet", detail: "Arrow function", insertText: "const ${1:fn} = (${2:params}) => {\n\t$0\n};", isSnippet: true },
  { label: "forof", kind: "snippet", detail: "for...of loop", insertText: "for (const ${1:item} of ${2:iterable}) {\n\t$0\n}", isSnippet: true },
];

const CSHARP_COMPLETIONS: CompletionEntry[] = [
  { label: "abstract", kind: "keyword", detail: "keyword" },
  { label: "async", kind: "keyword", detail: "keyword" },
  { label: "await", kind: "keyword", detail: "keyword" },
  { label: "bool", kind: "type", detail: "primitive type" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "byte", kind: "type", detail: "primitive type" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "char", kind: "type", detail: "primitive type" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "public class ${1:ClassName}\n{\n\t$0\n}", isSnippet: true },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "decimal", kind: "type", detail: "primitive type" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "double", kind: "type", detail: "primitive type" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "float", kind: "type", detail: "primitive type" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (int ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++)\n{\n\t$0\n}", isSnippet: true },
  { label: "foreach", kind: "keyword", detail: "keyword", insertText: "foreach (var ${1:item} in ${2:collection})\n{\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition})\n{\n\t$0\n}", isSnippet: true },
  { label: "int", kind: "type", detail: "primitive type" },
  { label: "interface", kind: "keyword", detail: "keyword" },
  { label: "internal", kind: "keyword", detail: "keyword" },
  { label: "long", kind: "type", detail: "primitive type" },
  { label: "namespace", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "object", kind: "type", detail: "type" },
  { label: "override", kind: "keyword", detail: "keyword" },
  { label: "private", kind: "keyword", detail: "keyword" },
  { label: "protected", kind: "keyword", detail: "keyword" },
  { label: "public", kind: "keyword", detail: "keyword" },
  { label: "readonly", kind: "keyword", detail: "keyword" },
  { label: "record", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "string", kind: "type", detail: "string type" },
  { label: "struct", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try\n{\n\t$1\n}\ncatch (Exception ex)\n{\n\t$0\n}", isSnippet: true },
  { label: "using", kind: "keyword", detail: "keyword" },
  { label: "var", kind: "type", detail: "type deduction" },
  { label: "void", kind: "type", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while (${1:condition})\n{\n\t$0\n}", isSnippet: true },

  // C# Standard
  { label: "Console", kind: "class", detail: "System.Console" },
  { label: "WriteLine", kind: "function", detail: "Console.WriteLine()", insertText: "Console.WriteLine($1);", isSnippet: true },
  { label: "ReadLine", kind: "function", detail: "Console.ReadLine()" },
  { label: "List", kind: "class", detail: "List<T>", insertText: "List<${1:int}> ${2:list} = new List<${1:int}>();", isSnippet: true },
  { label: "Dictionary", kind: "class", detail: "Dictionary<TKey, TValue>" },
  { label: "Math", kind: "class", detail: "System.Math" },
  { label: "Convert", kind: "class", detail: "System.Convert" },

  // Snippets
  { label: "cw", kind: "snippet", detail: "Console.WriteLine", insertText: "Console.WriteLine($1);", isSnippet: true },
  { label: "svm", kind: "snippet", detail: "Main method", insertText: "static void Main(string[] args)\n{\n\t$0\n}", isSnippet: true },
];

const GO_COMPLETIONS: CompletionEntry[] = [
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "chan", kind: "keyword", detail: "keyword" },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "defer", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "fallthrough", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for ${1:i} := 0; ${1:i} < ${2:n}; ${1:i}++ {\n\t$0\n}", isSnippet: true },
  { label: "func", kind: "keyword", detail: "keyword", insertText: "func ${1:name}(${2:params}) ${3:returnType} {\n\t$0\n}", isSnippet: true },
  { label: "go", kind: "keyword", detail: "keyword" },
  { label: "goto", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if ${1:condition} {\n\t$0\n}", isSnippet: true },
  { label: "import", kind: "keyword", detail: "keyword", insertText: "import (\n\t\"${1:fmt}\"\n)", isSnippet: true },
  { label: "interface", kind: "keyword", detail: "keyword" },
  { label: "map", kind: "keyword", detail: "keyword" },
  { label: "package", kind: "keyword", detail: "keyword", insertText: "package ${1:main}\n\n", isSnippet: true },
  { label: "range", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "select", kind: "keyword", detail: "keyword" },
  { label: "struct", kind: "keyword", detail: "keyword", insertText: "type ${1:Name} struct {\n\t$0\n}", isSnippet: true },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "type", kind: "keyword", detail: "keyword" },
  { label: "var", kind: "keyword", detail: "keyword" },
  { label: "nil", kind: "keyword", detail: "nil" },
  { label: "true", kind: "keyword", detail: "true" },
  { label: "false", kind: "keyword", detail: "false" },
  { label: "iota", kind: "keyword", detail: "iota" },

  // Built-in types & functions
  { label: "fmt", kind: "module", detail: "fmt package" },
  { label: "Println", kind: "function", detail: "fmt.Println()", insertText: "fmt.Println($1)", isSnippet: true },
  { label: "Printf", kind: "function", detail: "fmt.Printf()", insertText: "fmt.Printf(\"${1:%v}\\n\", ${2:var})", isSnippet: true },
  { label: "make", kind: "function", detail: "make(t Type, size ...IntegerType)" },
  { label: "append", kind: "function", detail: "append(slice, elems...)", insertText: "append(${1:slice}, ${2:elem})", isSnippet: true },
  { label: "len", kind: "function", detail: "len(v)" },
  { label: "cap", kind: "function", detail: "cap(v)" },
  { label: "delete", kind: "function", detail: "delete(m, key)" },
  { label: "panic", kind: "function", detail: "panic(v)" },
  { label: "recover", kind: "function", detail: "recover()" },

  // Snippets
  { label: "main", kind: "snippet", detail: "main() function", insertText: "func main() {\n\t$0\n}", isSnippet: true },
  { label: "forr", kind: "snippet", detail: "for range loop", insertText: "for ${1:i}, ${2:val} := range ${3:slice} {\n\t$0\n}", isSnippet: true },
  { label: "iferr", kind: "snippet", detail: "if err != nil", insertText: "if err != nil {\n\treturn ${1:err}\n}", isSnippet: true },
];

const RUST_COMPLETIONS: CompletionEntry[] = [
  { label: "as", kind: "keyword", detail: "keyword" },
  { label: "async", kind: "keyword", detail: "keyword" },
  { label: "await", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "crate", kind: "keyword", detail: "keyword" },
  { label: "dyn", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword", insertText: "enum ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "extern", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "fn", kind: "keyword", detail: "keyword", insertText: "fn ${1:name}(${2:params}) -> ${3:ReturnType} {\n\t$0\n}", isSnippet: true },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for ${1:item} in ${2:iterable} {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if ${1:condition} {\n\t$0\n}", isSnippet: true },
  { label: "impl", kind: "keyword", detail: "keyword", insertText: "impl ${1:Type} {\n\t$0\n}", isSnippet: true },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "let", kind: "keyword", detail: "keyword", insertText: "let ${1:mut }${2:name} = ${3:value};", isSnippet: true },
  { label: "loop", kind: "keyword", detail: "keyword" },
  { label: "match", kind: "keyword", detail: "keyword", insertText: "match ${1:expr} {\n\t${2:pattern} => ${3:result},\n\t_ => $0,\n}", isSnippet: true },
  { label: "mod", kind: "keyword", detail: "keyword" },
  { label: "mut", kind: "keyword", detail: "keyword" },
  { label: "pub", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "self", kind: "keyword", detail: "keyword" },
  { label: "Self", kind: "type", detail: "type" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "struct", kind: "keyword", detail: "keyword", insertText: "struct ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "trait", kind: "keyword", detail: "keyword", insertText: "trait ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "type", kind: "keyword", detail: "keyword" },
  { label: "unsafe", kind: "keyword", detail: "keyword" },
  { label: "use", kind: "keyword", detail: "keyword" },
  { label: "where", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword", insertText: "while ${1:condition} {\n\t$0\n}", isSnippet: true },

  // Macros & Types
  { label: "println!", kind: "function", detail: "println!(...)", insertText: "println!(\"${1:{}}\", ${2:var});", isSnippet: true },
  { label: "print!", kind: "function", detail: "print!(...)" },
  { label: "vec!", kind: "function", detail: "vec![...]", insertText: "vec![${1:elements}]", isSnippet: true },
  { label: "format!", kind: "function", detail: "format!(...)" },
  { label: "Vec", kind: "class", detail: "Vec<T>" },
  { label: "String", kind: "class", detail: "String" },
  { label: "Option", kind: "class", detail: "Option<T>" },
  { label: "Some", kind: "function", detail: "Some(v)" },
  { label: "None", kind: "variable", detail: "None" },
  { label: "Result", kind: "class", detail: "Result<T, E>" },
  { label: "Ok", kind: "function", detail: "Ok(v)" },
  { label: "Err", kind: "function", detail: "Err(e)" },
  { label: "HashMap", kind: "class", detail: "std::collections::HashMap" },

  // Snippets
  { label: "main", kind: "snippet", detail: "main() function", insertText: "fn main() {\n\t$0\n}", isSnippet: true },
];

const KOTLIN_COMPLETIONS: CompletionEntry[] = [
  { label: "as", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName} {\n\t$0\n}", isSnippet: true },
  { label: "data class", kind: "snippet", detail: "data class", insertText: "data class ${1:Name}(\n\tval ${2:prop}: ${3:String}\n)", isSnippet: true },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (${1:item} in ${2:collection}) {\n\t$0\n}", isSnippet: true },
  { label: "fun", kind: "keyword", detail: "keyword", insertText: "fun ${1:name}(${2:params}): ${3:Unit} {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "interface", kind: "keyword", detail: "keyword" },
  { label: "is", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "object", kind: "keyword", detail: "keyword" },
  { label: "package", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword" },
  { label: "typealias", kind: "keyword", detail: "keyword" },
  { label: "val", kind: "keyword", detail: "read-only variable", insertText: "val ${1:name} = ${2:value}", isSnippet: true },
  { label: "var", kind: "keyword", detail: "mutable variable", insertText: "var ${1:name} = ${2:value}", isSnippet: true },
  { label: "when", kind: "keyword", detail: "keyword", insertText: "when (${1:x}) {\n\t${2:1} -> ${3:print(1)}\n\telse -> $0\n}", isSnippet: true },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "println", kind: "function", detail: "println()", insertText: "println($1)", isSnippet: true },
  { label: "print", kind: "function", detail: "print()" },
  { label: "readLine", kind: "function", detail: "readLine()" },
  { label: "listOf", kind: "function", detail: "listOf()" },
  { label: "mutableListOf", kind: "function", detail: "mutableListOf()" },
  { label: "mapOf", kind: "function", detail: "mapOf()" },
  { label: "main", kind: "snippet", detail: "main() function", insertText: "fun main() {\n\t$0\n}", isSnippet: true },
];

const SWIFT_COMPLETIONS: CompletionEntry[] = [
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "deinit", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "extension", kind: "keyword", detail: "keyword" },
  { label: "func", kind: "keyword", detail: "keyword", insertText: "func ${1:name}(${2:params}) -> ${3:ReturnType} {\n\t$0\n}", isSnippet: true },
  { label: "import", kind: "keyword", detail: "keyword" },
  { label: "init", kind: "keyword", detail: "keyword" },
  { label: "let", kind: "keyword", detail: "constant", insertText: "let ${1:name} = ${2:value}", isSnippet: true },
  { label: "protocol", kind: "keyword", detail: "keyword" },
  { label: "struct", kind: "keyword", detail: "keyword", insertText: "struct ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "var", kind: "keyword", detail: "variable", insertText: "var ${1:name} = ${2:value}", isSnippet: true },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "defer", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for ${1:item} in ${2:collection} {\n\t$0\n}", isSnippet: true },
  { label: "guard", kind: "keyword", detail: "keyword", insertText: "guard ${1:condition} else {\n\treturn\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if ${1:condition} {\n\t$0\n}", isSnippet: true },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "print", kind: "function", detail: "print()", insertText: "print($1)", isSnippet: true },
];

const PHP_COMPLETIONS: CompletionEntry[] = [
  { label: "abstract", kind: "keyword", detail: "keyword" },
  { label: "array", kind: "keyword", detail: "keyword" },
  { label: "as", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName} {\n\t$0\n}", isSnippet: true },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "die", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "echo", kind: "keyword", detail: "keyword", insertText: "echo \"${1:Hello}\\n\";", isSnippet: true },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "elseif", kind: "keyword", detail: "keyword" },
  { label: "exit", kind: "keyword", detail: "keyword" },
  { label: "extends", kind: "keyword", detail: "keyword" },
  { label: "final", kind: "keyword", detail: "keyword" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "fn", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (\\$${1:i} = 0; \\$${1:i} < ${2:n}; \\$${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "foreach", kind: "keyword", detail: "keyword", insertText: "foreach (\\$${1:array} as \\$${2:item}) {\n\t$0\n}", isSnippet: true },
  { label: "function", kind: "keyword", detail: "keyword", insertText: "function ${1:name}(${2:params}) {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "implements", kind: "keyword", detail: "keyword" },
  { label: "interface", kind: "keyword", detail: "keyword" },
  { label: "namespace", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "private", kind: "keyword", detail: "keyword" },
  { label: "protected", kind: "keyword", detail: "keyword" },
  { label: "public", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "variable", detail: "\\$this" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword", insertText: "try {\n\t$1\n} catch (Exception \\$${2:e}) {\n\t$0\n}", isSnippet: true },
  { label: "use", kind: "keyword", detail: "keyword" },
  { label: "var", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "strlen", kind: "function", detail: "strlen(string)" },
  { label: "count", kind: "function", detail: "count(countable)" },
  { label: "print_r", kind: "function", detail: "print_r(value)" },
  { label: "var_dump", kind: "function", detail: "var_dump(value)" },
];

const RUBY_COMPLETIONS: CompletionEntry[] = [
  { label: "alias", kind: "keyword", detail: "keyword" },
  { label: "and", kind: "keyword", detail: "keyword" },
  { label: "begin", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:ClassName}\n\tdef initialize(${2:args})\n\t\t$0\n\tend\nend", isSnippet: true },
  { label: "def", kind: "keyword", detail: "keyword", insertText: "def ${1:method_name}(${2:args})\n\t$0\nend", isSnippet: true },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "elsif", kind: "keyword", detail: "keyword" },
  { label: "end", kind: "keyword", detail: "keyword" },
  { label: "ensure", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword" },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if ${1:condition}\n\t$0\nend", isSnippet: true },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "module", kind: "keyword", detail: "keyword" },
  { label: "next", kind: "keyword", detail: "keyword" },
  { label: "nil", kind: "keyword", detail: "keyword" },
  { label: "not", kind: "keyword", detail: "keyword" },
  { label: "or", kind: "keyword", detail: "keyword" },
  { label: "rescue", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "self", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "unless", kind: "keyword", detail: "keyword" },
  { label: "until", kind: "keyword", detail: "keyword" },
  { label: "when", kind: "keyword", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "yield", kind: "keyword", detail: "keyword" },
  { label: "puts", kind: "function", detail: "puts", insertText: "puts $1", isSnippet: true },
  { label: "print", kind: "function", detail: "print" },
  { label: "gets", kind: "function", detail: "gets.chomp" },
];

const SCALA_COMPLETIONS: CompletionEntry[] = [
  { label: "abstract", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "def", kind: "keyword", detail: "keyword", insertText: "def ${1:name}(${2:params}): ${3:Unit} = {\n\t$0\n}", isSnippet: true },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "extends", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "final", kind: "keyword", detail: "keyword" },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (${1:i} <- ${2:0 until n}) {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword" },
  { label: "implicit", kind: "keyword", detail: "keyword" },
  { label: "import", kind: "keyword", detail: "keyword" },
  { label: "lazy", kind: "keyword", detail: "keyword" },
  { label: "match", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "object", kind: "keyword", detail: "keyword", insertText: "object ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "override", kind: "keyword", detail: "keyword" },
  { label: "package", kind: "keyword", detail: "keyword" },
  { label: "private", kind: "keyword", detail: "keyword" },
  { label: "protected", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "sealed", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "trait", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword" },
  { label: "type", kind: "keyword", detail: "keyword" },
  { label: "val", kind: "keyword", detail: "immutable value", insertText: "val ${1:name} = ${2:value}", isSnippet: true },
  { label: "var", kind: "keyword", detail: "mutable variable", insertText: "var ${1:name} = ${2:value}", isSnippet: true },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "with", kind: "keyword", detail: "keyword" },
  { label: "yield", kind: "keyword", detail: "keyword" },
  { label: "println", kind: "function", detail: "println()", insertText: "println($1)", isSnippet: true },
];

const DART_COMPLETIONS: CompletionEntry[] = [
  { label: "abstract", kind: "keyword", detail: "keyword" },
  { label: "as", kind: "keyword", detail: "keyword" },
  { label: "assert", kind: "keyword", detail: "keyword" },
  { label: "async", kind: "keyword", detail: "keyword" },
  { label: "await", kind: "keyword", detail: "keyword" },
  { label: "break", kind: "keyword", detail: "keyword" },
  { label: "case", kind: "keyword", detail: "keyword" },
  { label: "catch", kind: "keyword", detail: "keyword" },
  { label: "class", kind: "keyword", detail: "keyword", insertText: "class ${1:Name} {\n\t$0\n}", isSnippet: true },
  { label: "const", kind: "keyword", detail: "keyword" },
  { label: "continue", kind: "keyword", detail: "keyword" },
  { label: "default", kind: "keyword", detail: "keyword" },
  { label: "do", kind: "keyword", detail: "keyword" },
  { label: "dynamic", kind: "type", detail: "dynamic type" },
  { label: "else", kind: "keyword", detail: "keyword" },
  { label: "enum", kind: "keyword", detail: "keyword" },
  { label: "extends", kind: "keyword", detail: "keyword" },
  { label: "extension", kind: "keyword", detail: "keyword" },
  { label: "false", kind: "keyword", detail: "keyword" },
  { label: "final", kind: "keyword", detail: "keyword", insertText: "final ${1:name} = ${2:value};", isSnippet: true },
  { label: "finally", kind: "keyword", detail: "keyword" },
  { label: "for", kind: "keyword", detail: "keyword", insertText: "for (var ${1:i} = 0; ${1:i} < ${2:n}; ${1:i}++) {\n\t$0\n}", isSnippet: true },
  { label: "if", kind: "keyword", detail: "keyword", insertText: "if (${1:condition}) {\n\t$0\n}", isSnippet: true },
  { label: "implements", kind: "keyword", detail: "keyword" },
  { label: "import", kind: "keyword", detail: "keyword" },
  { label: "in", kind: "keyword", detail: "keyword" },
  { label: "is", kind: "keyword", detail: "keyword" },
  { label: "late", kind: "keyword", detail: "keyword" },
  { label: "mixin", kind: "keyword", detail: "keyword" },
  { label: "new", kind: "keyword", detail: "keyword" },
  { label: "null", kind: "keyword", detail: "keyword" },
  { label: "return", kind: "keyword", detail: "keyword" },
  { label: "static", kind: "keyword", detail: "keyword" },
  { label: "super", kind: "keyword", detail: "keyword" },
  { label: "switch", kind: "keyword", detail: "keyword" },
  { label: "this", kind: "keyword", detail: "keyword" },
  { label: "throw", kind: "keyword", detail: "keyword" },
  { label: "true", kind: "keyword", detail: "keyword" },
  { label: "try", kind: "keyword", detail: "keyword" },
  { label: "var", kind: "keyword", detail: "keyword", insertText: "var ${1:name} = ${2:value};", isSnippet: true },
  { label: "void", kind: "type", detail: "keyword" },
  { label: "while", kind: "keyword", detail: "keyword" },
  { label: "print", kind: "function", detail: "print()", insertText: "print($1);", isSnippet: true },
  { label: "main", kind: "snippet", detail: "main() function", insertText: "void main() {\n\t$0\n}", isSnippet: true },
];

const SQL_COMPLETIONS: CompletionEntry[] = [
  { label: "SELECT", kind: "keyword", detail: "keyword", insertText: "SELECT ${1:*} FROM ${2:table_name};", isSnippet: true },
  { label: "FROM", kind: "keyword", detail: "keyword" },
  { label: "WHERE", kind: "keyword", detail: "keyword", insertText: "WHERE ${1:condition}", isSnippet: true },
  { label: "INSERT INTO", kind: "keyword", detail: "keyword", insertText: "INSERT INTO ${1:table} (${2:columns}) VALUES (${3:values});", isSnippet: true },
  { label: "UPDATE", kind: "keyword", detail: "keyword", insertText: "UPDATE ${1:table} SET ${2:col} = ${3:val} WHERE ${4:condition};", isSnippet: true },
  { label: "DELETE FROM", kind: "keyword", detail: "keyword", insertText: "DELETE FROM ${1:table} WHERE ${2:condition};", isSnippet: true },
  { label: "CREATE TABLE", kind: "keyword", detail: "keyword", insertText: "CREATE TABLE ${1:table_name} (\n\t${2:id} INT PRIMARY KEY AUTO_INCREMENT,\n\t${0}\n);", isSnippet: true },
  { label: "ALTER TABLE", kind: "keyword", detail: "keyword" },
  { label: "DROP TABLE", kind: "keyword", detail: "keyword" },
  { label: "JOIN", kind: "keyword", detail: "keyword" },
  { label: "INNER JOIN", kind: "keyword", detail: "keyword", insertText: "INNER JOIN ${1:table} ON ${2:condition}", isSnippet: true },
  { label: "LEFT JOIN", kind: "keyword", detail: "keyword", insertText: "LEFT JOIN ${1:table} ON ${2:condition}", isSnippet: true },
  { label: "RIGHT JOIN", kind: "keyword", detail: "keyword" },
  { label: "FULL OUTER JOIN", kind: "keyword", detail: "keyword" },
  { label: "GROUP BY", kind: "keyword", detail: "keyword", insertText: "GROUP BY ${1:column}", isSnippet: true },
  { label: "ORDER BY", kind: "keyword", detail: "keyword", insertText: "ORDER BY ${1:column} ${2:ASC}", isSnippet: true },
  { label: "HAVING", kind: "keyword", detail: "keyword" },
  { label: "LIMIT", kind: "keyword", detail: "keyword" },
  { label: "OFFSET", kind: "keyword", detail: "keyword" },
  { label: "DISTINCT", kind: "keyword", detail: "keyword" },
  { label: "AS", kind: "keyword", detail: "keyword" },
  { label: "AND", kind: "keyword", detail: "keyword" },
  { label: "OR", kind: "keyword", detail: "keyword" },
  { label: "NOT", kind: "keyword", detail: "keyword" },
  { label: "IN", kind: "keyword", detail: "keyword" },
  { label: "BETWEEN", kind: "keyword", detail: "keyword" },
  { label: "LIKE", kind: "keyword", detail: "keyword" },
  { label: "IS NULL", kind: "keyword", detail: "keyword" },
  { label: "IS NOT NULL", kind: "keyword", detail: "keyword" },
  { label: "UNION", kind: "keyword", detail: "keyword" },
  { label: "UNION ALL", kind: "keyword", detail: "keyword" },
  { label: "COUNT", kind: "function", detail: "COUNT(*)", insertText: "COUNT(${1:*})", isSnippet: true },
  { label: "SUM", kind: "function", detail: "SUM(col)", insertText: "SUM(${1:column})", isSnippet: true },
  { label: "AVG", kind: "function", detail: "AVG(col)", insertText: "AVG(${1:column})", isSnippet: true },
  { label: "MIN", kind: "function", detail: "MIN(col)", insertText: "MIN(${1:column})", isSnippet: true },
  { label: "MAX", kind: "function", detail: "MAX(col)", insertText: "MAX(${1:column})", isSnippet: true },
  { label: "PRIMARY KEY", kind: "keyword", detail: "constraint" },
  { label: "FOREIGN KEY", kind: "keyword", detail: "constraint" },
];

const HTML_COMPLETIONS: CompletionEntry[] = [
  { label: "html5", kind: "snippet", detail: "HTML5 Boilerplate", insertText: "<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n\t<meta charset=\"UTF-8\">\n\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n\t<title>${1:Document}</title>\n</head>\n<body>\n\t$0\n</body>\n</html>", isSnippet: true },
  { label: "div", kind: "snippet", detail: "<div></div>", insertText: "<div class=\"${1:container}\">\n\t$0\n</div>", isSnippet: true },
  { label: "span", kind: "snippet", detail: "<span></span>", insertText: "<span>$0</span>", isSnippet: true },
  { label: "p", kind: "snippet", detail: "<p></p>", insertText: "<p>$0</p>", isSnippet: true },
  { label: "h1", kind: "snippet", detail: "<h1></h1>", insertText: "<h1>$0</h1>", isSnippet: true },
  { label: "h2", kind: "snippet", detail: "<h2></h2>", insertText: "<h2>$0</h2>", isSnippet: true },
  { label: "h3", kind: "snippet", detail: "<h3></h3>", insertText: "<h3>$0</h3>", isSnippet: true },
  { label: "button", kind: "snippet", detail: "<button></button>", insertText: "<button type=\"button\" class=\"${1:btn}\">$2</button>", isSnippet: true },
  { label: "input", kind: "snippet", detail: "<input />", insertText: "<input type=\"${1:text}\" placeholder=\"${2:Enter value}\" />", isSnippet: true },
  { label: "form", kind: "snippet", detail: "<form></form>", insertText: "<form action=\"${1:#}\" method=\"${2:POST}\">\n\t$0\n</form>", isSnippet: true },
  { label: "ul", kind: "snippet", detail: "<ul><li></li></ul>", insertText: "<ul>\n\t<li>$0</li>\n</ul>", isSnippet: true },
  { label: "ol", kind: "snippet", detail: "<ol><li></li></ol>", insertText: "<ol>\n\t<li>$0</li>\n</ol>", isSnippet: true },
  { label: "table", kind: "snippet", detail: "<table>", insertText: "<table>\n\t<thead>\n\t\t<tr>\n\t\t\t<th>${1:Header}</th>\n\t\t</tr>\n\t</thead>\n\t<tbody>\n\t\t<tr>\n\t\t\t<td>${2:Data}</td>\n\t\t</tr>\n\t</tbody>\n</table>", isSnippet: true },
  { label: "a", kind: "snippet", detail: "<a href=''></a>", insertText: "<a href=\"${1:#}\">${2:Link}</a>", isSnippet: true },
  { label: "img", kind: "snippet", detail: "<img src='' alt='' />", insertText: "<img src=\"${1:url}\" alt=\"${2:alt}\" />", isSnippet: true },
];

const CSS_COMPLETIONS: CompletionEntry[] = [
  { label: "display", kind: "keyword", detail: "display: flex | grid | block | none", insertText: "display: ${1:flex};", isSnippet: true },
  { label: "flex-center", kind: "snippet", detail: "Center with flexbox", insertText: "display: flex;\njustify-content: center;\nalign-items: center;", isSnippet: true },
  { label: "grid-cols", kind: "snippet", detail: "Grid columns", insertText: "display: grid;\ngrid-template-columns: repeat(${1:3}, 1fr);\ngap: ${2:1rem};", isSnippet: true },
  { label: "justify-content", kind: "keyword", detail: "justify-content", insertText: "justify-content: ${1:center};", isSnippet: true },
  { label: "align-items", kind: "keyword", detail: "align-items", insertText: "align-items: ${1:center};", isSnippet: true },
  { label: "margin", kind: "keyword", detail: "margin", insertText: "margin: ${1:0};", isSnippet: true },
  { label: "padding", kind: "keyword", detail: "padding", insertText: "padding: ${1:1rem};", isSnippet: true },
  { label: "border-radius", kind: "keyword", detail: "border-radius", insertText: "border-radius: ${1:8px};", isSnippet: true },
  { label: "background-color", kind: "keyword", detail: "background-color", insertText: "background-color: ${1:#ffffff};", isSnippet: true },
  { label: "color", kind: "keyword", detail: "color", insertText: "color: ${1:#333333};", isSnippet: true },
  { label: "font-size", kind: "keyword", detail: "font-size", insertText: "font-size: ${1:14px};", isSnippet: true },
  { label: "box-shadow", kind: "keyword", detail: "box-shadow", insertText: "box-shadow: 0 ${1:4px} ${2:6px} rgba(0, 0, 0, ${3:0.1});", isSnippet: true },
  { label: "transition", kind: "keyword", detail: "transition", insertText: "transition: all 0.2s ease-in-out;", isSnippet: true },
];

const LANGUAGE_MAP: Record<string, CompletionEntry[]> = {
  java: JAVA_COMPLETIONS,
  cpp: CPP_COMPLETIONS,
  c: C_COMPLETIONS,
  python: PYTHON_COMPLETIONS,
  javascript: JAVASCRIPT_COMPLETIONS,
  typescript: JAVASCRIPT_COMPLETIONS,
  csharp: CSHARP_COMPLETIONS,
  go: GO_COMPLETIONS,
  rust: RUST_COMPLETIONS,
  kotlin: KOTLIN_COMPLETIONS,
  swift: SWIFT_COMPLETIONS,
  php: PHP_COMPLETIONS,
  ruby: RUBY_COMPLETIONS,
  scala: SCALA_COMPLETIONS,
  dart: DART_COMPLETIONS,
  sql: SQL_COMPLETIONS,
  html: HTML_COMPLETIONS,
  css: CSS_COMPLETIONS,
};

let registered = false;

export function registerMonacoCompletions(monaco: MonacoInstance) {
  if (!monaco) return;

  // Define custom themes with distinct gutter styling matching modern IDEs
  try {
    monaco.editor.defineTheme("lms-light", {
      base: "vs",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "0000FF", fontStyle: "bold" },
        { token: "keyword.control", foreground: "0000FF", fontStyle: "bold" },
        { token: "type", foreground: "005577" },
        { token: "type.identifier", foreground: "005577" },
        { token: "class", foreground: "1A365D", fontStyle: "bold" },
        { token: "identifier", foreground: "1E293B" },
        { token: "function", foreground: "795E26" },
        { token: "string", foreground: "0969DA" },
        { token: "string.escape", foreground: "D73A49" },
        { token: "comment", foreground: "6E7781", fontStyle: "italic" },
        { token: "number", foreground: "098658" },
        { token: "operator", foreground: "000000" },
        { token: "delimiter", foreground: "24292F" },
      ],
      colors: {
        "editor.background": "#FFFFFF",
        "editorGutter.background": "#F5F6F8",
        "editorLineNumber.foreground": "#8C95A6",
        "editorLineNumber.activeForeground": "#0F172A",
        "editor.lineHighlightBackground": "#EBF5FF", // Soft MNC-style active line highlight
        "editor.lineHighlightBorder": "#00000000",
        "editorCursor.foreground": "#0055FF",
        "editorIndentGuide.background": "#E2E8F0",
        "editorIndentGuide.activeBackground": "#94A3B8",
        "editorOverviewRuler.border": "#00000000",
        "editorRuler.foreground": "#F1F5F9",
        "editorBracketMatch.background": "#D0E5FC",
        "editorBracketMatch.border": "#93C5FD",
      },
    });

    monaco.editor.defineTheme("lms-dark", {
      base: "vs-dark",
      inherit: true,
      rules: [
        { token: "keyword", foreground: "569CD6", fontStyle: "bold" },
        { token: "type", foreground: "4EC9B0" },
        { token: "class", foreground: "4EC9B0", fontStyle: "bold" },
        { token: "function", foreground: "DCDCAA" },
        { token: "string", foreground: "CE9178" },
        { token: "comment", foreground: "6A9955", fontStyle: "italic" },
        { token: "number", foreground: "B5CEA8" },
        { token: "annotation", foreground: "DCDCAA" },
        { token: "variable", foreground: "9CDCFE" },
      ],
      colors: {
        "editor.background": "#141417",
        "editorGutter.background": "#18181C",
        "editorLineNumber.foreground": "#52525B",
        "editorLineNumber.activeForeground": "#F4F4F5",
        "editor.lineHighlightBackground": "#1E293B80",
        "editor.lineHighlightBorder": "#00000000",
        "editorCursor.foreground": "#60A5FA",
        "editorBracketMatch.background": "#1E3A5F",
        "editorBracketMatch.border": "#3B82F6",
        "editorIndentGuide.background": "#27272A",
        "editorIndentGuide.activeBackground": "#52525B",
        "editor.selectionBackground": "#2563EB40",
      },
    });
  } catch (e) {
    console.warn("[Monaco] Failed to register custom themes:", e);
  }

  if (registered || !monaco.languages) return;
  registered = true;

  const mapKind = (kindStr?: string): Monaco.languages.CompletionItemKind => {
    switch (kindStr) {
      case "keyword":
        return monaco.languages.CompletionItemKind.Keyword;
      case "class":
        return monaco.languages.CompletionItemKind.Class;
      case "function":
        return monaco.languages.CompletionItemKind.Function;
      case "snippet":
        return monaco.languages.CompletionItemKind.Snippet;
      case "type":
        return monaco.languages.CompletionItemKind.TypeParameter;
      case "variable":
        return monaco.languages.CompletionItemKind.Variable;
      case "interface":
        return monaco.languages.CompletionItemKind.Interface;
      case "module":
        return monaco.languages.CompletionItemKind.Module;
      default:
        return monaco.languages.CompletionItemKind.Keyword;
    }
  };

  const { formatSourceCode } = require("./compiler/code-formatter");

  Object.entries(LANGUAGE_MAP).forEach(([langId, entries]) => {
    try {
      // 1. Register Code Auto-Completions
      monaco.languages.registerCompletionItemProvider(langId, {
        provideCompletionItems: (model, position) => {
          const word = model.getWordUntilPosition(position);
          const range: Monaco.IRange = {
            startLineNumber: position.lineNumber,
            endLineNumber: position.lineNumber,
            startColumn: word.startColumn,
            endColumn: word.endColumn,
          };

          const suggestions: Monaco.languages.CompletionItem[] = entries.map((entry) => ({
            label: entry.label,
            kind: mapKind(entry.kind),
            detail: entry.detail || entry.kind || "keyword",
            documentation: entry.documentation || (entry.detail ? `${entry.label} (${entry.detail})` : entry.label),
            insertText: entry.insertText || entry.label,
            insertTextRules: entry.isSnippet
              ? monaco.languages.CompletionItemInsertTextRule.InsertAsSnippet
              : undefined,
            range,
            sortText: entry.kind === "snippet" ? "20" : entry.kind === "keyword" ? "10" : "15",
          }));

          return { suggestions };
        },
      });

      // 2. Register Native Document Formatting (Shift + Alt + F)
      monaco.languages.registerDocumentFormattingEditProvider(langId, {
        provideDocumentFormattingEdits: (model, options) => {
          const fullText = model.getValue();
          const formatted = formatSourceCode(fullText, langId, {
            tabSize: options.tabSize,
            insertSpaces: options.insertSpaces,
          });

          return [
            {
              range: model.getFullModelRange(),
              text: formatted,
            },
          ];
        },
      });
    } catch (e) {
      console.warn(`[Monaco] Failed to register completions/formatting for language ${langId}:`, e);
    }
  });
}
