import type { ReportSummary, StudentReportItem } from "@/app/api/admin/reports/student-performance/route";

/**
 * Clean CSV cell escaping complying with RFC 4180
 */
function escapeCsv(val: any): string {
  if (val === null || val === undefined) return '""';
  const str = String(val);
  if (str.includes('"') || str.includes(",") || str.includes("\n") || str.includes("\r")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return `"${str}"`;
}

/**
 * Generates and downloads a multi-sheet Enterprise Excel workbook (.xlsx)
 */
export async function exportReportToExcel(
  summary: ReportSummary,
  students: StudentReportItem[],
  customFilename?: string
): Promise<void> {
  const XLSX = await import("xlsx");
  const wb = XLSX.utils.book_new();

  // ══════════════════════════════════════════════════════════════
  // SHEET 1: EXECUTIVE SUMMARY
  // ══════════════════════════════════════════════════════════════
  const genDateFormatted = new Date(summary.generatedAt).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const summaryAoa: any[][] = [
    ["FALCON LEARNING TECHNOLOGIES • SENSI GROUP"],
    ["Enterprise Student Performance & Analytics Executive Summary"],
    [],
    ["REPORT METADATA", ""],
    ["Report Scope", summary.scope],
    ["Report Mode", summary.reportType.toUpperCase()],
    ["Target Batch", summary.batchName || "All Batches"],
    ["Status Filter", summary.filtersApplied.status.toUpperCase()],
    ["Date Range Filter", summary.filtersApplied.dateRange.toUpperCase()],
    ["Generated Timestamp", genDateFormatted],
    ["Generated By", summary.generatedBy],
    [],
    ["SYSTEM AGGREGATED METRICS", "VALUE"],
    ["Total Enrolled Students", summary.totalStudents],
    ["Active Students Count", summary.activeStudents],
    ["Inactive / Suspended Students", summary.inactiveStudents],
    ["Flagged Proctoring Alerts", summary.flaggedStudents],
    ["System Average Test Score", `${summary.averageScore}%`],
    ["Average Practice Track Accuracy", `${summary.averagePracticeScore}%`],
    ["Average Algorithmic Coding Accuracy", `${summary.averageCodingAccuracy}%`],
    ["Average Exam / Assessment Score", `${summary.averageAssessmentScore}%`],
    ["Total Project / Assignment Submissions", summary.totalAssignmentsSubmitted],
    ["Overall Course Completion Rate", `${summary.courseCompletionRate}%`],
    ["Average Proctoring Compliance Rating", `${summary.averageProctoringCompliance}%`],
    ["Total Flagged Violations Logged", summary.totalViolationsLogged],
    ["Total Cumulative Active Learning Time", summary.totalActiveTimeFormatted],
    ["Average Active Time per Candidate", summary.averageActiveTimeFormatted],
  ];

  const wsSummary = XLSX.utils.aoa_to_sheet(summaryAoa);
  wsSummary["!cols"] = [{ wch: 38 }, { wch: 34 }];
  XLSX.utils.book_append_sheet(wb, wsSummary, "Summary");

  // ══════════════════════════════════════════════════════════════
  // SHEET 2: STUDENT PERFORMANCE ROSTER
  // ══════════════════════════════════════════════════════════════
  const studentHeaders = [
    "Student Name",
    "Email Address",
    "Employee ID",
    "Assigned Batch",
    "Department",
    "Account Status",
    "Enrolled Courses",
    "Completed Courses",
    "Course Titles",
    "Average Score (%)",
    "Practice Score (%)",
    "Practice Challenges",
    "Coding Accuracy (%)",
    "Problems Solved",
    "Coding Submissions",
    "Assessment Score (%)",
    "Assessments Taken",
    "Assignments Submitted",
    "Proctoring Compliance (%)",
    "Violations Logged",
    "Active Learning Time",
    "Last Activity",
    "Overall Performance (%)",
    "Performance Tier",
  ];

  const studentRows = students.map((s) => [
    s.name,
    s.email,
    s.employeeId,
    s.batch,
    s.department,
    s.status.toUpperCase(),
    s.enrolledCoursesCount,
    s.completedCoursesCount,
    s.courseTitles.join(", ") || "None",
    s.avgScore !== null ? `${s.avgScore}%` : "No evaluations",
    s.practiceScore !== null ? `${s.practiceScore}%` : "No practice activity",
    s.practiceCount,
    s.codingAccuracy !== null ? `${s.codingAccuracy}%` : "No coding activity",
    s.codingSolvedCount,
    s.codingSubmissionsCount,
    s.assessmentScore !== null ? `${s.assessmentScore}%` : "No exam records",
    s.assessmentCount,
    s.assignmentCount,
    `${s.proctoringCompliance}%`,
    s.violationCount,
    s.activeTimeFormatted,
    s.lastActivity,
    s.overallPerformancePct !== null ? `${s.overallPerformancePct}%` : "Pending Data",
    s.overallStatus,
  ]);

  const wsStudents = XLSX.utils.aoa_to_sheet([studentHeaders, ...studentRows]);
  wsStudents["!cols"] = [
    { wch: 22 }, // Name
    { wch: 30 }, // Email
    { wch: 14 }, // Emp ID
    { wch: 20 }, // Batch
    { wch: 16 }, // Dept
    { wch: 14 }, // Status
    { wch: 16 }, // Enrolled
    { wch: 16 }, // Completed
    { wch: 32 }, // Course Titles
    { wch: 18 }, // Avg Score
    { wch: 18 }, // Practice
    { wch: 18 }, // Practice Count
    { wch: 18 }, // Coding Acc
    { wch: 16 }, // Solved
    { wch: 18 }, // Subs
    { wch: 20 }, // Exam Score
    { wch: 18 }, // Exams Taken
    { wch: 22 }, // Assignments
    { wch: 24 }, // Proctoring
    { wch: 18 }, // Violations
    { wch: 20 }, // Active Time
    { wch: 18 }, // Last Activity
    { wch: 22 }, // Overall Perf
    { wch: 18 }, // Status
  ];

  XLSX.utils.book_append_sheet(wb, wsStudents, "Student Performance");

  // ══════════════════════════════════════════════════════════════
  // SHEET 3: BATCH LEVEL SUMMARY
  // ══════════════════════════════════════════════════════════════
  const batchAggregation = new Map<string, {
    count: number;
    activeCount: number;
    scores: number[];
    codingSolved: number;
    activeTime: number;
  }>();

  students.forEach((s) => {
    const bName = s.batch || "Unassigned";
    const current = batchAggregation.get(bName) || {
      count: 0,
      activeCount: 0,
      scores: [],
      codingSolved: 0,
      activeTime: 0,
    };
    current.count += 1;
    if (s.status === "active") current.activeCount += 1;
    if (s.avgScore !== null) current.scores.push(s.avgScore);
    current.codingSolved += s.codingSolvedCount;
    current.activeTime += s.activeTimeSeconds;
    batchAggregation.set(bName, current);
  });

  const batchHeaders = [
    "Batch Name",
    "Total Candidates",
    "Active Candidates",
    "Average Test Score (%)",
    "Total Coding Solves",
    "Cumulative Learning Time",
    "Average Time / Candidate",
  ];

  const batchRows: any[][] = [];
  batchAggregation.forEach((data, bName) => {
    const avgScore =
      data.scores.length > 0
        ? Math.round(data.scores.reduce((a, b) => a + b, 0) / data.scores.length)
        : 0;
    const avgTimeSecs = data.count > 0 ? Math.round(data.activeTime / data.count) : 0;

    batchRows.push([
      bName,
      data.count,
      data.activeCount,
      `${avgScore}%`,
      data.codingSolved,
      formatSeconds(data.activeTime),
      formatSeconds(avgTimeSecs),
    ]);
  });

  const wsBatches = XLSX.utils.aoa_to_sheet([batchHeaders, ...batchRows]);
  wsBatches["!cols"] = [
    { wch: 26 },
    { wch: 18 },
    { wch: 18 },
    { wch: 22 },
    { wch: 20 },
    { wch: 26 },
    { wch: 24 },
  ];
  XLSX.utils.book_append_sheet(wb, wsBatches, "Batch Analytics");

  // Determine Safe Filename
  const cleanScope = summary.scope.replace(/[^a-zA-Z0-9_-]/g, "_");
  const dateStamp = new Date().toISOString().slice(0, 10);
  const fileName = customFilename || `FALCON_Student_Performance_${cleanScope}_${dateStamp}.xlsx`;

  XLSX.writeFile(wb, fileName);
}

function formatSeconds(secs: number): string {
  if (!secs || secs <= 0) return "0m";
  const hours = Math.floor(secs / 3600);
  const minutes = Math.floor((secs % 3600) / 60);
  if (hours > 0) return `${hours}h ${minutes}m`;
  return `${minutes}m`;
}

/**
 * Generates and downloads a clean UTF-8 CSV with BOM for universal Excel compatibility
 */
export function exportReportToCSV(
  summary: ReportSummary,
  students: StudentReportItem[],
  customFilename?: string
): void {
  const headers = [
    "Student Name",
    "Email Address",
    "Employee ID",
    "Assigned Batch",
    "Department",
    "Account Status",
    "Enrolled Courses",
    "Completed Courses",
    "Course Titles",
    "Average Score",
    "Practice Score",
    "Practice Challenges",
    "Coding Accuracy",
    "Problems Solved",
    "Coding Submissions",
    "Assessment Score",
    "Assessments Taken",
    "Assignments Submitted",
    "Proctoring Compliance",
    "Violations Logged",
    "Active Learning Time",
    "Last Activity",
    "Overall Performance",
    "Performance Tier",
  ];

  const rows = students.map((s) => [
    escapeCsv(s.name),
    escapeCsv(s.email),
    escapeCsv(s.employeeId),
    escapeCsv(s.batch),
    escapeCsv(s.department),
    escapeCsv(s.status.toUpperCase()),
    s.enrolledCoursesCount,
    s.completedCoursesCount,
    escapeCsv(s.courseTitles.join("; ") || "None"),
    escapeCsv(s.avgScore !== null ? `${s.avgScore}%` : "No evaluations"),
    escapeCsv(s.practiceScore !== null ? `${s.practiceScore}%` : "No practice activity"),
    s.practiceCount,
    escapeCsv(s.codingAccuracy !== null ? `${s.codingAccuracy}%` : "No coding activity"),
    s.codingSolvedCount,
    s.codingSubmissionsCount,
    escapeCsv(s.assessmentScore !== null ? `${s.assessmentScore}%` : "No exam records"),
    s.assessmentCount,
    s.assignmentCount,
    escapeCsv(`${s.proctoringCompliance}%`),
    s.violationCount,
    escapeCsv(s.activeTimeFormatted),
    escapeCsv(s.lastActivity),
    escapeCsv(s.overallPerformancePct !== null ? `${s.overallPerformancePct}%` : "Pending Data"),
    escapeCsv(s.overallStatus),
  ]);

  const csvContent = "\uFEFF" + [
    headers.map(escapeCsv).join(","),
    ...rows.map((r) => r.join(",")),
  ].join("\r\n");

  const blob = new Blob([csvContent], { type: "text/csv;charset=utf-8;" });
  const cleanScope = summary.scope.replace(/[^a-zA-Z0-9_-]/g, "_");
  const dateStamp = new Date().toISOString().slice(0, 10);
  const fileName = customFilename || `FALCON_Student_Performance_${cleanScope}_${dateStamp}.csv`;

  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", fileName);
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Generates and downloads a clean, professional enterprise PDF
 * formatted with official SENSI Group / FALCON header and styled table.
 */
export async function exportReportToPDF(
  summary: ReportSummary,
  students: StudentReportItem[],
  customFilename?: string
): Promise<void> {
  const genDateFormatted = new Date(summary.generatedAt).toLocaleString("en-US", {
    dateStyle: "medium",
    timeStyle: "short",
  });

  const cleanScope = summary.scope.replace(/[^a-zA-Z0-9_-]/g, "_");
  const dateStamp = new Date().toISOString().slice(0, 10);
  const fileName = customFilename || `FALCON_Student_Performance_${cleanScope}_${dateStamp}.pdf`;

  // Build high-fidelity print window with exact enterprise layout
  const printWindow = window.open("", "_blank");
  if (!printWindow) {
    throw new Error("Could not open print window. Please allow popups for report export.");
  }

  const htmlContent = `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${fileName}</title>
  <style>
    @page {
      size: A4 landscape;
      margin: 14mm 12mm 14mm 12mm;
    }
    body {
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
      color: #111827;
      background: #FFFFFF;
      margin: 0;
      padding: 0;
      font-size: 11px;
      line-height: 1.4;
    }
    .header-bar {
      display: flex;
      justify-content: space-between;
      align-items: flex-start;
      border-bottom: 2px solid #1E3A8A;
      padding-bottom: 12px;
      margin-bottom: 16px;
    }
    .brand-title {
      font-size: 20px;
      font-weight: 900;
      color: #1E3A8A;
      letter-spacing: -0.5px;
      margin: 0;
    }
    .brand-subtitle {
      font-size: 10px;
      color: #4B5563;
      font-weight: 600;
      margin: 2px 0 0 0;
      text-transform: uppercase;
      letter-spacing: 0.5px;
    }
    .report-title {
      font-size: 14px;
      font-weight: 800;
      color: #111827;
      margin: 8px 0 2px 0;
    }
    .meta-box {
      text-align: right;
      font-size: 10px;
      color: #4B5563;
    }
    .meta-box strong {
      color: #111827;
    }
    .kpi-grid {
      display: grid;
      grid-template-columns: repeat(4, 1fr);
      gap: 10px;
      margin-bottom: 16px;
    }
    .kpi-card {
      background: #F9FAFB;
      border: 1px solid #E5E7EB;
      border-radius: 8px;
      padding: 10px 12px;
    }
    .kpi-label {
      font-size: 9px;
      color: #6B7280;
      font-weight: 700;
      text-transform: uppercase;
      margin: 0 0 4px 0;
    }
    .kpi-value {
      font-size: 16px;
      font-weight: 800;
      color: #111827;
      margin: 0;
    }
    .kpi-sub {
      font-size: 9px;
      color: #059669;
      font-weight: 600;
      margin-top: 2px;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin-top: 8px;
      font-size: 10px;
    }
    th {
      background: #F3F4F6;
      color: #374151;
      font-weight: 700;
      text-align: left;
      padding: 7px 8px;
      border: 1px solid #E5E7EB;
      font-size: 9px;
      text-transform: uppercase;
      letter-spacing: 0.3px;
    }
    td {
      padding: 6px 8px;
      border: 1px solid #E5E7EB;
      vertical-align: middle;
    }
    tr:nth-child(even) td {
      background: #F9FAFB;
    }
    .badge {
      display: inline-block;
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 9px;
      font-weight: 700;
      text-align: center;
    }
    .badge-success { background: #ECFDF5; color: #065F46; border: 1px solid #A7F3D0; }
    .badge-primary { background: #EFF6FF; color: #1E40AF; border: 1px solid #BFDBFE; }
    .badge-warning { background: #FFFBEB; color: #92400E; border: 1px solid #FDE68A; }
    .badge-danger  { background: #FEF2F2; color: #991B1B; border: 1px solid #FECACA; }
    .footer {
      margin-top: 20px;
      border-top: 1px solid #E5E7EB;
      padding-top: 8px;
      display: flex;
      justify-content: space-between;
      font-size: 9px;
      color: #6B7280;
    }
    @media print {
      body { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="header-bar">
    <div>
      <h1 class="brand-title">FALCON</h1>
      <p class="brand-subtitle">Learning Technologies • SENSI Group</p>
      <div class="report-title">Student Performance & Enterprise Analytics Report</div>
      <div style="font-size: 10px; color: #4B5563; margin-top: 2px;">
        Scope: <strong>${summary.scope}</strong> • Filter: <strong>${summary.filtersApplied.status.toUpperCase()}</strong> • Range: <strong>${summary.filtersApplied.dateRange.toUpperCase()}</strong>
      </div>
    </div>
    <div class="meta-box">
      <div>Generated: <strong>${genDateFormatted}</strong></div>
      <div>Generated By: <strong>${summary.generatedBy}</strong></div>
      <div>Total Candidates: <strong>${summary.totalStudents}</strong></div>
      <div style="margin-top: 4px;" class="no-print">
        <button onclick="window.print()" style="padding: 5px 12px; background: #1E3A8A; color: white; border: none; border-radius: 4px; font-weight: bold; cursor: pointer;">Print / Save as PDF</button>
      </div>
    </div>
  </div>

  <div class="kpi-grid">
    <div class="kpi-card">
      <div class="kpi-label">Total Candidates</div>
      <div class="kpi-value">${summary.totalStudents}</div>
      <div class="kpi-sub">${summary.activeStudents} Active (${summary.totalStudents > 0 ? Math.round((summary.activeStudents / summary.totalStudents) * 100) : 0}%)</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Average Test Score</div>
      <div class="kpi-value">${summary.averageScore}%</div>
      <div class="kpi-sub">Practice: ${summary.averagePracticeScore}% • Coding: ${summary.averageCodingAccuracy}%</div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Proctoring Compliance</div>
      <div class="kpi-value">${summary.averageProctoringCompliance}%</div>
      <div class="kpi-sub" style="color: ${summary.totalViolationsLogged > 0 ? '#DC2626' : '#059669'};">
        ${summary.totalViolationsLogged > 0 ? `${summary.totalViolationsLogged} Violations Logged` : 'Clean Record (0 Alerts)'}
      </div>
    </div>
    <div class="kpi-card">
      <div class="kpi-label">Cumulative Active Time</div>
      <div class="kpi-value">${summary.totalActiveTimeFormatted}</div>
      <div class="kpi-sub">Avg / Candidate: ${summary.averageActiveTimeFormatted}</div>
    </div>
  </div>

  <table>
    <thead>
      <tr>
        <th style="width: 22%;">Candidate Details</th>
        <th style="width: 14%;">Assigned Batch</th>
        <th style="width: 9%;">Avg Score</th>
        <th style="width: 9%;">Practice</th>
        <th style="width: 9%;">Coding</th>
        <th style="width: 9%;">Exams</th>
        <th style="width: 8%;">Projects</th>
        <th style="width: 10%;">Active Time</th>
        <th style="width: 10%; text-align: center;">Status</th>
      </tr>
    </thead>
    <tbody>
      ${students.map((s) => `
        <tr>
          <td>
            <div style="font-weight: 700; color: #111827;">${s.name}</div>
            <div style="color: #6B7280; font-size: 9px;">${s.email} • <span style="font-family: monospace;">${s.employeeId}</span></div>
          </td>
          <td><span class="badge badge-primary">${s.batch}</span></td>
          <td><strong>${s.avgScore !== null ? `${s.avgScore}%` : '—'}</strong></td>
          <td>${s.practiceScore !== null ? `${s.practiceScore}%` : '—'}</td>
          <td>${s.codingAccuracy !== null ? `${s.codingAccuracy}% (${s.codingSolvedCount})` : '—'}</td>
          <td>${s.assessmentScore !== null ? `${s.assessmentScore}%` : '—'}</td>
          <td>${s.assignmentCount} submitted</td>
          <td>${s.activeTimeFormatted}</td>
          <td style="text-align: center;">
            <span class="badge ${
              s.overallStatus === 'Excellent'
                ? 'badge-success'
                : s.overallStatus === 'Good'
                ? 'badge-primary'
                : s.overallStatus === 'Average'
                ? 'badge-warning'
                : 'badge-danger'
            }">
              ${s.overallStatus}
            </span>
          </td>
        </tr>
      `).join("")}
    </tbody>
  </table>

  <div class="footer">
    <div>FALCON Learning Technologies • Enterprise Analytics Engine • Confidential</div>
    <div>Report Document Generated: ${genDateFormatted} • All database records verified</div>
  </div>

  <script>
    window.onload = function() {
      setTimeout(function() {
        window.print();
      }, 500);
    };
  </script>
</body>
</html>
`;

  printWindow.document.open();
  printWindow.document.write(htmlContent);
  printWindow.document.close();
}
